version: 2
formats: all
build:
    os: ubuntu-24.04
    tools:
        python: "3.12"
    apt_packages:
        - dotnet-sdk-8.0
python:
  install:
    - requirements: docs/requirements.txt  
sphinx:
  configuration: docs/conf.py
